export const RESET_CART = 'RESET_CART';
export const DELETE_ITEM = 'DELETE_ITEM';
export const CHANGE_COUNT = 'CHANGE_COUNT';
export const SET_CHECKOUT_DETAILS = 'SET_CHECKOUT_DETAILS';
export const TOGGLE_NOTIFICATION = 'TOGGLE_NOTIFICATION';